# Generated by Django 5.2.9 on 2026-02-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField()),
                ('icon', models.ImageField(upload_to='')),
                ('order_position', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.rank'),
        ),
    ]
