# Generated by Django 6.0 on 2026-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rank_profile_current_rank_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='min_score',
            field=models.IntegerField(default=0),
        ),
    ]
