# Generated by Django 6.0 on 2026-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_rank_min_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
    ]
