# Generated by Django 6.0 on 2026-01-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='icon',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
