# Generated by Django 6.0 on 2026-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_rank_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='main_app/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
