# Generated by Django 6.0 on 2026-01-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_profile_avatar_alter_rank_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatars/'),
        ),
    ]
