# Generated by Django 6.0 on 2026-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='icon',
            field=models.ImageField(default='', upload_to='rank'),
        ),
    ]
